### ISSUE TITLE
[Question]About the mod's name

### ISSUE THREAD

**Issue by TUsama** [wildcardgamez/Buddycards-Core#4]
Ok, I've got a quite embarrassing question (don't worry, not a bug), so the mod name " buddy card", does it mean that a set of cards which can accompany you in the game? The reason I ask this is because of the CHS locale. It seems that the translator simply transliterates the "buddy card" to "巴迪卡", this makes me feel a little weird, I don't even know what's the meaning of it and, kinda funny, I'm Chinese. So I'll appreciate that if you could tell me the actual meaning of the mod's name.

**Comment by wildcardgamez** [comment]
A Buddycard is a term used to refer to every trading card in the mod. The name is a combination of the word buddy, which is because the cards are meant to be your buddy and friends, and each has its own personality. The second part of the name card should be more obvious, referring to the idea of trading cards as a whole. If this answers your question, let me know and I'll close this.

**Comment by TUsama** [comment]
thanks for your reply! I'm now totally figuring out what the name Buddycard wants to express.
